___
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [27]:
import numpy as np

#### Create an array of 10 zeros 

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [30]:
a = np.ones(10)
a *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [31]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [32]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
d=np.array([[[0,1,2],[3,4,5],[6,7,8]]])
d

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

#### Create a 3x3 identity matrix

In [34]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [35]:
np.random.rand(1)

array([0.34378179])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [36]:
np.random.randn(5,5)

array([[-0.6711581 ,  0.01982784,  1.2099377 ,  0.57691131,  0.26423241],
       [-0.91951872,  1.8950378 ,  1.07636833,  2.15233641,  0.84039123],
       [ 1.0677922 ,  0.4421381 , -0.95162371, -0.32257805, -0.65073461],
       [-0.23874716,  0.94477401, -1.36355709, -0.27917185,  0.06252956],
       [-0.55021652,  0.11692956,  0.86152584, -0.05977694, -1.30037288]])

#### Create the following matrix:

In [37]:
np.random.rand(1,101)

array([[4.45414487e-01, 7.91186918e-02, 4.17000767e-01, 2.71862160e-01,
        5.29916323e-01, 9.62475595e-01, 1.90642349e-01, 5.59626802e-01,
        1.73437232e-01, 8.84237664e-01, 4.95453880e-01, 1.76920918e-01,
        8.70052301e-01, 9.81142519e-01, 1.76973324e-01, 5.11331208e-04,
        3.06934194e-02, 2.09549399e-01, 9.17907186e-01, 6.51719846e-02,
        2.66693613e-01, 1.96846708e-01, 9.79861561e-01, 6.72837906e-01,
        5.20736470e-01, 2.37858231e-01, 8.13080602e-02, 5.90828621e-01,
        3.19309366e-01, 7.16138950e-02, 3.28569159e-01, 9.72077685e-01,
        9.24710418e-01, 5.05333554e-01, 5.10071482e-01, 7.73890446e-01,
        7.23916011e-01, 2.78459848e-01, 1.04958088e-01, 5.81443572e-01,
        5.51738263e-01, 3.31989100e-01, 1.73421548e-01, 9.46096073e-01,
        8.68339085e-01, 1.21052900e-01, 7.71719783e-01, 8.57296954e-01,
        9.66764891e-01, 8.57110315e-01, 4.29729168e-01, 5.46756155e-01,
        9.33322160e-01, 8.44101855e-01, 7.98852391e-01, 8.850180

#### Create an array of 20 linearly spaced points between 0 and 1:

In [38]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [39]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [41]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [42]:
mat[3,4]

20

In [43]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat=np.array([[1,2,3],[6,7,8],[11,12,32]])

In [44]:
print(mat[0,1])
print(mat[1,1])
print(mat[2,1])

2
7
12


In [45]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

In [46]:
mat[4]

array([21, 22, 23, 24, 25])

In [47]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

In [48]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [49]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [50]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [51]:
np.sum(mat, axis = 0)

array([55, 60, 65, 70, 75])

# Great Job!